// Generated by gencpp from file imu_driver/AngleResponse.msg
// DO NOT EDIT!


#ifndef IMU_DRIVER_MESSAGE_ANGLERESPONSE_H
#define IMU_DRIVER_MESSAGE_ANGLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_driver
{
template <class ContainerAllocator>
struct AngleResponse_
{
  typedef AngleResponse_<ContainerAllocator> Type;

  AngleResponse_()
    : angle(0.0)
    , std_dev_ang(0.0)
    , omega(0.0)
    , std_dev_omega(0.0)  {
    }
  AngleResponse_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , std_dev_ang(0.0)
    , omega(0.0)
    , std_dev_omega(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _std_dev_ang_type;
  _std_dev_ang_type std_dev_ang;

   typedef double _omega_type;
  _omega_type omega;

   typedef double _std_dev_omega_type;
  _std_dev_omega_type std_dev_omega;





  typedef boost::shared_ptr< ::imu_driver::AngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_driver::AngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AngleResponse_

typedef ::imu_driver::AngleResponse_<std::allocator<void> > AngleResponse;

typedef boost::shared_ptr< ::imu_driver::AngleResponse > AngleResponsePtr;
typedef boost::shared_ptr< ::imu_driver::AngleResponse const> AngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_driver::AngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_driver::AngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::AngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_driver::AngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::AngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_driver::AngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::AngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_driver::AngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_driver::AngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a46ad9d1acd29c33849f4ca4e749a514";
  }

  static const char* value(const ::imu_driver::AngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa46ad9d1acd29c33ULL;
  static const uint64_t static_value2 = 0x849f4ca4e749a514ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_driver::AngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_driver/AngleResponse";
  }

  static const char* value(const ::imu_driver::AngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_driver::AngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n\
float64 std_dev_ang\n\
float64 omega\n\
float64 std_dev_omega\n\
\n\
";
  }

  static const char* value(const ::imu_driver::AngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_driver::AngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.std_dev_ang);
      stream.next(m.omega);
      stream.next(m.std_dev_omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_driver::AngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_driver::AngleResponse_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "std_dev_ang: ";
    Printer<double>::stream(s, indent + "  ", v.std_dev_ang);
    s << indent << "omega: ";
    Printer<double>::stream(s, indent + "  ", v.omega);
    s << indent << "std_dev_omega: ";
    Printer<double>::stream(s, indent + "  ", v.std_dev_omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_DRIVER_MESSAGE_ANGLERESPONSE_H
