// Generated by gencpp from file point_creator/GetPoint.msg
// DO NOT EDIT!


#ifndef POINT_CREATOR_MESSAGE_GETPOINT_H
#define POINT_CREATOR_MESSAGE_GETPOINT_H

#include <ros/service_traits.h>


#include <point_creator/GetPointRequest.h>
#include <point_creator/GetPointResponse.h>


namespace point_creator
{

struct GetPoint
{

typedef GetPointRequest Request;
typedef GetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPoint
} // namespace point_creator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_creator::GetPoint > {
  static const char* value()
  {
    return "54e2ac5f870ad872ea553cca86512c19";
  }

  static const char* value(const ::point_creator::GetPoint&) { return value(); }
};

template<>
struct DataType< ::point_creator::GetPoint > {
  static const char* value()
  {
    return "point_creator/GetPoint";
  }

  static const char* value(const ::point_creator::GetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::point_creator::GetPointRequest> should match 
// service_traits::MD5Sum< ::point_creator::GetPoint > 
template<>
struct MD5Sum< ::point_creator::GetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_creator::GetPoint >::value();
  }
  static const char* value(const ::point_creator::GetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_creator::GetPointRequest> should match 
// service_traits::DataType< ::point_creator::GetPoint > 
template<>
struct DataType< ::point_creator::GetPointRequest>
{
  static const char* value()
  {
    return DataType< ::point_creator::GetPoint >::value();
  }
  static const char* value(const ::point_creator::GetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_creator::GetPointResponse> should match 
// service_traits::MD5Sum< ::point_creator::GetPoint > 
template<>
struct MD5Sum< ::point_creator::GetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_creator::GetPoint >::value();
  }
  static const char* value(const ::point_creator::GetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_creator::GetPointResponse> should match 
// service_traits::DataType< ::point_creator::GetPoint > 
template<>
struct DataType< ::point_creator::GetPointResponse>
{
  static const char* value()
  {
    return DataType< ::point_creator::GetPoint >::value();
  }
  static const char* value(const ::point_creator::GetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_CREATOR_MESSAGE_GETPOINT_H
